# Generated by Django 4.2.6 on 2023-10-29 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0005_alter_student_details_user_profileid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], default='P', max_length=1, verbose_name='Status')),
                ('student', models.ForeignKey(db_column='User ProfileId', on_delete=django.db.models.deletion.CASCADE, to='Main.student_details')),
            ],
        ),
    ]
