# Generated by Django 4.2.6 on 2023-10-30 18:41

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_student_details_user_profileid'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('due_date', models.DateField(null=True)),
                ('link_toupload', tinymce.models.HTMLField(null=True)),
                ('teacher', models.ForeignKey(db_column='User TProfileId', on_delete=django.db.models.deletion.CASCADE, to='Main.teacher_details')),
            ],
        ),
    ]
