# Generated by Django 5.1.2 on 2024-11-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_student_details_user_profileid'),
        ('teacher', '0003_alter_assignments_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendence_data',
            unique_together={('student', 'date')},
        ),
    ]
