# Generated by Django 5.1.2 on 2024-11-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_attendence_data_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendence_data',
            unique_together=set(),
        ),
    ]
