# Generated by Django 4.2.6 on 2023-10-26 12:08

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('image', models.FileField(default=None, upload_to='news/')),
                ('content', tinymce.models.HTMLField()),
                ('title_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('none', 'Select Gender'), ('male', 'Male'), ('female', 'Female'), ('trans', 'Other')], max_length=10, verbose_name='Gender')),
                ('photo', models.FileField(upload_to='user_photos/', verbose_name='Photo')),
                ('country_code', models.CharField(choices=[('+91', 'India (+91)'), ('+1', 'United States (+1)')], max_length=5, verbose_name='Country Code')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('father_name', models.CharField(max_length=100, verbose_name='Father Name')),
                ('mother_name', models.CharField(max_length=100, verbose_name='Mother Name')),
                ('Permanent_address', models.CharField(max_length=255, verbose_name='Permanent Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Details',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_teacher', models.CharField(default='B.tech', max_length=100, null=True, verbose_name='Class Teacher')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='Subject')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Salary')),
                ('dateofenrollment', models.DateTimeField(db_column='DateOfEnrollment', null=True, verbose_name='date of enrollment')),
                ('User_profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_branch', models.CharField(max_length=100, null=True, verbose_name='Class/Branch')),
                ('grade', models.CharField(max_length=10, null=True, verbose_name='Grade')),
                ('guardian_name', models.CharField(max_length=100, null=True, verbose_name='Guardian Name')),
                ('guardian_phone_number', models.CharField(max_length=15, verbose_name='Guardian Phone Number')),
                ('father_phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Father Phone Number')),
                ('mother_phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mother Phone Number')),
                ('User_profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.profile')),
            ],
        ),
    ]
