# Generated by Django 4.2.6 on 2023-10-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_remove_profile_first_name_remove_profile_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='guardian_phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Guardian Phone Number'),
        ),
    ]
