# Generated by Django 4.2.6 on 2023-10-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_student_details_guardian_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-date_of_birth'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='teacher_details',
            options={'ordering': ['-teacher_id'], 'verbose_name': 'Teacher_Details', 'verbose_name_plural': 'Teacher_Detailss'},
        ),
        migrations.AlterField(
            model_name='teacher_details',
            name='dateofenrollment',
            field=models.DateTimeField(null=True, verbose_name='date of enrollment'),
        ),
    ]
