# Generated by Django 4.2.6 on 2023-10-29 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_profile_options_alter_teacher_details_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='User_profileId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.profile', verbose_name='User profileId'),
        ),
    ]
