# Generated by Django 4.2.6 on 2023-10-29 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0005_alter_student_details_user_profileid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teache_subject_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=20, null=True)),
                ('Class', models.CharField(max_length=20, null=True)),
                ('student', models.ForeignKey(db_column='User SProfileId', on_delete=django.db.models.deletion.CASCADE, to='Main.student_details')),
                ('teacher', models.ForeignKey(db_column='User TProfileId', on_delete=django.db.models.deletion.CASCADE, to='Main.teacher_details')),
            ],
        ),
        migrations.CreateModel(
            name='primary_school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TELUGU', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10)),
                ('HINDI', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10)),
                ('ENGLISH', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10)),
                ('MATHS', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10)),
                ('SCIENCE', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10)),
                ('student', models.ForeignKey(db_column='User ProfileId', on_delete=django.db.models.deletion.CASCADE, to='Main.student_details')),
            ],
        ),
        migrations.CreateModel(
            name='high_school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TELUGU', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10)),
                ('HINDI', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10)),
                ('ENGLISH', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10)),
                ('MATHS_A', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10)),
                ('MATHS_B', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10)),
                ('PHYSICS', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10)),
                ('CHEMISTRY', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10)),
                ('BIOLOGY', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10)),
                ('student', models.ForeignKey(db_column='User ProfileId', on_delete=django.db.models.deletion.CASCADE, to='Main.student_details')),
            ],
        ),
    ]
