# Generated by Django 4.2.6 on 2023-10-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_student_details_user_profileid'),
        ('student', '0002_alter_high_school_biology_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gradesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=20, null=True)),
                ('grade', models.CharField(choices=[('10', 'A'), ('9', 'B'), ('8', 'C'), ('7', 'D'), ('6', 'E'), ('5', 'Fail')], default='Yes', max_length=10)),
                ('student', models.ForeignKey(db_column='User ProfileId', on_delete=django.db.models.deletion.CASCADE, to='Main.student_details')),
            ],
        ),
    ]
