# Generated by Django 4.2.6 on 2023-10-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_gradesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradesheet',
            name='grade',
            field=models.CharField(choices=[('10', 'A'), ('9', 'B'), ('8', 'C'), ('7', 'D'), ('6', 'E'), ('5', 'Fail'), ('0', 'Yes')], default='Yes', max_length=10),
        ),
    ]
