# Generated by Django 5.1.2 on 2024-11-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_student_details_user_profileid'),
        ('student', '0004_alter_gradesheet_grade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teache_subject_Class',
            new_name='Teacher_subject_Class',
        ),
        migrations.AlterField(
            model_name='gradesheet',
            name='grade',
            field=models.CharField(choices=[('10', 'A'), ('9', 'B'), ('8', 'C'), ('7', 'D'), ('6', 'E'), ('5', 'Fail'), ('0', 'not given')], default='not given', max_length=10),
        ),
        migrations.AlterField(
            model_name='high_school',
            name='BIOLOGY',
            field=models.CharField(choices=[('Biology', 'Yes'), ('no', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='high_school',
            name='CHEMISTRY',
            field=models.CharField(choices=[('Chemistry', 'Yes'), ('no', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='high_school',
            name='ENGLISH',
            field=models.CharField(choices=[('English', 'Yes'), ('no', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='high_school',
            name='HINDI',
            field=models.CharField(choices=[('Hindi', 'Yes'), ('no', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='high_school',
            name='MATHS_A',
            field=models.CharField(choices=[('Maths_a', 'Yes'), ('no', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='high_school',
            name='MATHS_B',
            field=models.CharField(choices=[('Maths_b', 'Yes'), ('no', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='high_school',
            name='PHYSICS',
            field=models.CharField(choices=[('Physics', 'Yes'), ('no', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='high_school',
            name='TELUGU',
            field=models.CharField(choices=[('Telugu', 'Yes'), ('no', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='primary_school',
            name='ENGLISH',
            field=models.CharField(choices=[('English', 'Yes'), ('no', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='primary_school',
            name='HINDI',
            field=models.CharField(choices=[('Hindi', 'Yes'), ('no', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='primary_school',
            name='MATHS',
            field=models.CharField(choices=[('Maths', 'Yes'), ('no', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='primary_school',
            name='SCIENCE',
            field=models.CharField(choices=[('Science', 'Yes'), ('no', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='primary_school',
            name='TELUGU',
            field=models.CharField(choices=[('Telugu', 'Yes'), ('no', 'No')], default='No', max_length=10),
        ),
    ]
